package db.sqlliteapp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import db.sqlliteapp.Users;
import db.sqlliteapp.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig UserDaoConfig;

    private final UserDao UserDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        UserDaoConfig = daoConfigMap.get(UserDao.class).clone();
        UserDaoConfig.initIdentityScope(type);

        UserDao = new UserDao(UserDaoConfig, this);

        registerDao(Users.class, UserDao);
    }
   
	public void clear() {
        UserDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return UserDao;
    }


}
