package db.sqlliteapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Users {

    private Long id;
    /** Not-null value. */
    private String name;
    private String email;
    private String address;
    private String city;
    private String pincode;
    private String comment;
    private java.util.Date date;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String name, String email, String address, String city, String pincode, String comment, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.address = address;
        this.city = city;
        this.pincode = pincode;        
        this.comment = comment;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }
    
    /** Not-null value. */
    public String getEmail() {
        return email;
    }
    
    /** Not-null value. */
    public String getAddress() {
        return address;
    }
    
    /** Not-null value. */
    public String getCity() {
        return city;
    }
    
    /** Not-null value. */
    public String getPincode() {
        return pincode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }
    
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }    
    
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }
    
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }
    
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
